// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';

export function Connect():Promise<void>;

export function Connected():Promise<boolean>;

export function GetStatus():Promise<core.SliderStatus>;

export function SendParams(arg1:core.SliderParams):Promise<void>;
