// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect() {
  return window['go']['main']['App']['Connect']();
}

export function Connected() {
  return window['go']['main']['App']['Connected']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function SendParams(arg1) {
  return window['go']['main']['App']['SendParams'](arg1);
}
